# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3498acbcef759950a1d41565e7ed99c42ac578fb61d71050fc135477ba7eb45ba27caf0802722334031e89fcd42f8397db621331149e90af4899bd7ba79a3b25

test:
  secret_key_base: 4c5497b045af1f502de8937dcdba2b0101877f44411d473780fc793eb63c7eaaf78b36de81122fdc925e0c5ba15729f5fa2a57386f9cc7f3f9fe1a854d9f4910

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
